### ISSUE TITLE
Please make the project exposes multiple YAML files to GraphQL nodes.

### ISSUE THREAD

**Issue by aaronamm** [jpedroschmitz/rocketdocs#120]
**What would you like to be added**:

Parameterize [typeName of gatsby-transformer-yaml plugin](https://github.com/jpedroschmitz/rocketdocs/blob/main/%40rocketseat/gatsby-theme-docs-core/gatsby-config.js?fbclid=IwAR00cTjXBC648-nY4MEUTfPme4L69h5OYlCaM3vvoRN202I3PbVH_f_8zzM#L30) or make it flexible that we can expose new YAML to new GraphQL node.

**Why is this needed**:

Since we set  typeName to static value `SidebarItems`, we cannot expose new YAML file to a new GraphQL node.

**Is your enhancement request related to a problem? Please describe.**

I would like to add new data stored in YAML and expose it as GraphQL node that I can query later.
However, adding `gatsby-transformer-yaml` plugin section in my custom gatsby-config doesn't help.
This is because it cannot override the existing ` typeName: 'SidebarItems'` and all new YML files will be merged to this type.
This also causes  an issue when trying to [query allSidebarItems in gast-by-node.js].(https://github.com/jpedroschmitz/rocketdocs/blob/main/%40rocketseat/gatsby-theme-docs-core/gatsby-node.js#L75)

**Additional context**

This screenshot took from my personal project that I added multiple YAML files and exposed them to GraphQL nodes.
I only use default type name of [gatsby-transformer-yaml](https://github.com/dotnetthailand/dotnetthailand.github.io/blob/main/gatsby-config.js#L120)

![image](https://user-images.githubusercontent.com/2938310/146238490-909aedb8-27be-43c1-80d9-aa067f2de8fa.png)

**Comment by jpedroschmitz** [comment]
Could you open a PR for it?

We can add a new option for this.

**Comment by aaronamm** [comment]
@jpedroschmitz That's okay. Thank you.

**Comment by aaronamm** [comment]
@jpedroschmitz PR's opened #124 
Thanks.

**Comment by jpedroschmitz** [comment]
A new version that supports this feature was released!

Thanks a lot for your work on this @aaronamm ❤️
