### ISSUE TITLE
Creating an Index.mdx

### ISSUE THREAD

**Issue by MargaretCatter** [jpedroschmitz/rocketdocs#132]
## Summary

I'm trying to create an index.mdx file for my site. I followed the directions about putting it in `C:\Users\***\***\***\GitHub_HeroPrinny\mcatterdev--rocketdocs--gatsby\src\@rocketseat\gatsby-theme-docs\text` and nothing happened nothing changed. I tried changing the base directory within the gatsby-config.js file as well because I honestly don't think I'm going to be using much of the shadowing and really want to advance to turn it off completely (but that's beyond the scope of this issue).

I've cleared the cache as well and nothing changed. I also tried to see as an experiment what would happen if I changed the site color and nothing changed when I changed the hex code.

**Comment by jpedroschmitz** [comment]
Can you share your repo? Or a reproducible example? 
It should be working because our example is rendering the file just fine.


Take a look into this example: https://github.com/jpedroschmitz/rocketdocs/tree/main/examples/gatsby-theme-docs/src
