### ISSUE TITLE
Can we expect an upgrade to 5.7.0?

### ISSUE THREAD

**Issue by dannymk** [jpedroschmitz/rocketdocs#149]
Running a newer version of Gatsby and really looking forward to using this theme.  Will we be seeing an upgrade to V5.x.x?

**Comment by jpedroschmitz** [comment]
I plan to work on it soon, but feel free to start a PR if you want to contribute! That'd be very much appreciated!

**Comment by jpedroschmitz** [comment]
With the release of #150 on #153, the theme will support Gatsby v5!

Thanks for the great work, @tekmaven! It wouldn't be possible without your help!

**Comment by jpedroschmitz** [comment]
Here's a small migration guide for version 4 of the theme:

- [Follow Gatsby v4 > v5 upgrade guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/) (including upgrading to Node 18 and updating packages).
- Move the homepage from `src/@rocketseat/gatsby-theme-docs/text/index.mdx` to `src/home/index.mdx` and add `homePath: 'src/home'` in the plugin options.
